### ISSUE TITLE
Unable to process command `::add-path::/nix/var/nix/profiles/per-user/runner/profile/bin`

### ISSUE THREAD

**Issue by drupol** [numtide/nix-unstable-installer#21]
**Describe the bug**

Hello,

I'm trying to use the Github action in my workflow and I'm having this issue:

```
Error: Unable to process command '::add-path::/nix/var/nix/profiles/per-user/runner/profile/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/nix/var/nix/profiles/default/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**To Reproduce**

Copy paste the Github actions from the README file and try to use them.

**Potential solution**

Update the README file with a working example.

Context to see this happening: https://github.com/drupol/nixos-x260/runs/4296364526?

**Comment by lilyinstarlight** [comment]
Hi there!

This is actually an issue in the older version of [cachix/install-nix-action](https://github.com/cachix/install-nix-action), specifically versions 11 and below (see cachix/install-nix-action#50)

I've updated the README.md.erb file (from which the README.md file is automatically generated) for it in #20, but there hasn't been an unstable version of Nix that passed the Hydra tests yet so the README.md hasn't been regenerated since I fixed it

Could you try replacing `cachix/install-nix-action@v11` with `cachix/install-nix-action@v16` and see if you still get the error? (rather than enabling insecure GitHub Actions commands)

**Comment by drupol** [comment]
Thanks, perfectly working ! https://github.com/drupol/cv/runs/4300578055

**Comment by drupol** [comment]
I enabled dependabot on my repository so it updates github actions through automatic pull requests! Maybe we should do the same here?

**Comment by lilyinstarlight** [comment]
> Thanks, perfectly working !

Awesome!!

> I enabled dependabot on my repository so it updates github actions through automatic pull requests! Maybe we should do the same here?

I had been considering the same thing, but I haven't looked into it yet because I worry it'll only update the actual workflow and not the README.md.erb file that generates the readme. Do you know if you could get dependabot to update lines like this? https://github.com/numtide/nix-unstable-installer/blob/12853dce9959bc3ada0108924df56c0336be309c/README.md.erb#L37

Also about your PR, I think it could bring value to update the readme until the Hydra failures are resolved (they've been failing since mid-October and no one seems to currently be working on a fix) so you are welcome to update the PR to have a later version of cachix/install-nix-action in the readme

**Comment by lilyinstarlight** [comment]
I guess it would also be possible to just have the `update.rb` script template in the latest version or whatever version is currently used in the upload/test workflow in this repository

**Comment by drupol** [comment]
> I had been considering the same thing, but I haven't looked into it yet because I worry it'll only update the actual workflow and not the README.md.erb file that generates the readme. Do you know if you could get dependabot to update lines like this?
The best way to achieve this is to use semantic versioning, so we could use

With my better consideration, I think this is not the proper direction to tackle the issue.

However, I think you should update the versioning scheme of your GH action and use [semantic versioning](https://semver.org/).

Then, with:

```yaml
 - uses: cachix/install-nix-action@v1
```

And it would automatically download the latest version and there is no need to update the README file anymore.

WDYT ?

**Comment by lilyinstarlight** [comment]
Semantic versioning is not a bad idea, it would just have to be brought up at https://github.com/cachix/install-nix-action rather than here (also that sort of versioning is additionally dependant on the repository keeping a `v1` tag up to date for all v1.x.x releases)

The README.md file already gets automatically updated with each Nix unstable update by the script (based on an ERB template) so adding in the version from the `update.rb` script shouldn't be the worst thing ever. It is just a bit of an unfortunate situation though. I think I may work on adding Dependabot and just pulling whatever version the release workflow uses into the README.md file too on updates. The updates shouldn't be infrequent, but again they've been having test failures on macOS in Hydra the last month and this repo only updates for clean builds

Thoughts on that?

**Comment by drupol** [comment]
Maybe @domenkozar might have a word on this as well ?

Regarding the `update.rb`, how about doing something like [this](https://github.com/drupol/nixos-x260/blob/master/.github/workflows/upgrade-flakes.yaml) and replace the step `Make changes to pull request` with the relevant command?
